services:
  app:
    build:
      context: .
    labels:
      app: "ielts-playground"
    container_name: ielts-playground-documentizer
    environment:
      - NEXT_PUBLIC_SERVER_BASE_URL=$NEXT_PUBLIC_SERVER_BASE_URL
    ports:
      - $PORT:3000
    restart: always
